[package]
name = "wgpu-framebuffer"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13.0"
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.11"

[lints.clippy]
all = "deny"
perf = "deny"
complexity = "warn"
pedantic = "warn"
